# Generated by Django 5.2.1 on 2025-05-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrix', '0003_research_participant_researchquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='question_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
