# Generated by Django 5.2.1 on 2025-05-23 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrix', '0005_alter_question_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrix.question')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrix.research')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses_given', to='metrix.participant')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses_received', to='metrix.participant')),
            ],
        ),
    ]
