# Generated by Django 5.2.1 on 2025-05-23 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrix', '0006_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='research',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='metrix.research'),
        ),
    ]
