# Generated by Django 5.2.1 on 2025-05-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrix', '0007_alter_response_research'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
